version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: crm_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crm_db
    ports:
      - "5432:5432"
    volumes:
      - crm_db_data:/var/lib/postgresql/data
    networks:
      - crm-network

networks:
  crm-network:
    driver: bridge

volumes:
  crm_db_data:
